version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql-workflow
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - ${DB_PORT}:3306
    volumes:
        - ./conf/my.cnf:/etc/workflow-infra/conf.d/my.cnf
        - ./ddl:/docker-entrypoint-initdb.d